---
#
# The factory_reset button allows you to remotely invalidate (reset) all ESPHome preferences
# stored in flash memory and reboot your node. 
# After reboot all states, parameters and variables will be reinitialized with their default values. 
#
# https://esphome.io/components/button/factory_reset.html
#

platform: factory_reset
name: "${name} factory reset"