esphome:
  on_boot:
    - priority: 600
      then:
          - if:
              condition:
                and:
                  - sensor.in_range:
                      id: temperature_bas
                      below: 59.0
                  - sensor.in_range:
                      id: temperature_haut
                      below: 59.0
              then:
                - switch.turn_off: force_60
              else:
                - switch.turn_on: force_60
     
pcf8574:
  - id: 'pcf8574_hub'
    address: 0x20
    pcf8575: true

sensor:

  - id: !extend temperature_bas
    on_value_range:
      - below: 59.0
        then:
          - if:
              condition:
                sensor.in_range:
                  id: temperature_haut
                  below: 59.0
              then:
                - switch.turn_off: force_60
      - above: 60.5
        then:
          - switch.turn_on: force_60
 
    
  - id: !extend temperature_haut
    on_value_range:
      - below: 59.0
        then:
          - if:
              condition:
                sensor.in_range:
                  id: temperature_bas
                  below: 59.0
              then:
                - switch.turn_off: force_60
      - above: 60.5
        then:
          - switch.turn_on: force_60
 
    
switch:
  - platform: gpio
    id: force_60
    #Relais
    name: "Forçage 60°"
    pin:
      pcf8574: pcf8574_hub
      number: 12
      mode:
        output: true
      inverted: true
 
