esphome:
  on_boot:
    - priority: 600
      then:
          - if:
              condition:
                and:
                  - sensor.in_range:
                      id: temperature_bas
                      below: 59.0
                  - sensor.in_range:
                      id: temperature_haut
                      below: 59.0
              then:
                - switch.turn_off: force_60
              else:
                - switch.turn_on: force_60
     

sensor:
  - id: !extend temperature_bas
    on_value_range:
      - below: 59.0
        then:
          - if:
              condition:
                sensor.in_range:
                  id: temperature_haut
                  below: 59.0
              then:
                - switch.turn_off: force_60
      - above: 60.5
        then:
          - switch.turn_on: force_60
 
    
  - id: !extend temperature_haut
    on_value_range:
      - below: 59.0
        then:
          - if:
              condition:
                sensor.in_range:
                  id: temperature_bas
                  below: 59.0
              then:
                - switch.turn_off: force_60
      - above: 60.5
        then:
          - switch.turn_on: force_60

binary_sensor: 
  - platform: gpio
    name: "Résistance appoint"
    id: resistance_appoint
    device_class: heat
    pin:
      number: GPIO${version == "V1.0" and "32" or "36"}
      mode: INPUT
      inverted: False
    filters:
      - delayed_on: 1s
      - delayed_off: 1s
    
switch:
  - platform: gpio
    id: force_60
    #Relais
    name: "Forçage 60°"
    pin:
      number: GPIO33
      mode: OUTPUT
 
