substitutions:
  ## Personnalisation
  # 1/ Décommenter la ligne qui correspond au T.one connecté à la TOUG
  # slug: toug-aquaair # T.One AquaAIR
  # slug: toug-air # T.One AIR 
  
  # 2/ (optionnel) Remplacer le nom et la description par défaut si besoin
  # name: Mon Nom Perso # (friendly_name)
  # description: Mettre ici la description de remplacement


## Customization area
##### My customization - Start #####
##### My customization - End #####

## Choix et téléchargement de la configuration ESPHome
packages:
  remote_package:
    url: https://github.com/djtef/toug
    ref: main
    refresh: 300s
    files:
      # 3/ Décommenter la configuration à télécharger
      # - esphome/toug_air_eth.yaml               #T.One AIR avec connexion ethernet
      # - esphome/toug_air_wifi.yaml              #T.One AIR avec connexion wifi
      # - esphome/toug_aquaair_eth.yaml             #T.One AquaAIR avec connexion ethernet
      # - esphome/toug_aquaair_wifi.yaml          #T.One AquaAIR avec connexion wifi
      # - esphome/toug_aquaair_routeur_wifi.yaml  #T.One AquaAIR avec connexion ethernet et routeur solaire
      # - esphome/toug_aquaair_routeur_eth.yaml   #T.One AquaAIR avec connexion wifi et routeur solaire
