substitutions:
  slug: toug-aquaair
  name: TOUG AquaAIR
  description: Passerelle wifi locale pour le T.one AquaAIR avec routeur solaire
  
packages:
  # <<: !include_dir_named common
  board: !include boards/wt32-eth01_ethernet.yaml
  device: !include devices/tone_aquaair.yaml
  option: !include devices/tone_routeur.yaml
  