substitutions:
  slug: toug-air
  name: TOUG AIR
  description: Passerelle wifi locale pour le T.one AIR
  
packages:
  # <<: !include_dir_named common
  board: !include boards/wt32-eth01_wifi.yaml
  device: !include devices/tone_air.yaml
  