substitutions:
  slug: toug-aquaair
  name: TOUG AquaAIR
  description: Passerelle ethernet locale pour le T.one AquaAIR
  
packages:
  # <<: !include_dir_named common
  board: !include boards/wt32-eth01_ethernet.yaml
  device: !include devices/tone_aquaair.yaml
  